# This is a basic workflow to help you get started with Actions

name: string operations

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      string_to_process:
        required: true
        default: 'Test'
      function_name:
        required: true
        default: 'toUpperCase()'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Call string conversion
        id: convert-string
        uses: jaydattd/string-operations-action@main
        with:
          string_to_process: ${{ inputs.string_to_process }}
          function_name: ${{ inputs.function_name }}

      - name: Get the output conversion
        run: echo "Converted string is ${{ steps.convert-string.outputs.result }}"
